sourcegraph/code-intel-extensions

- src/handler.ts
Anything else required here?
Also: @chrismwendt how could you not have enabled Haskell yet 😄
> feat: add more language file extensions

- .travis.yml
- ci
- dev
- languages.ts
- package.json
- package/src/api.ts
- package/src/handler.test.ts
- package/src/handler.ts
- template/package.json
- template/src/extension.ts
- yarn.lock
Testing out a new `./ci` script.
> Add dev,ci scripts, parameterize sourcegraph dep for testing

- ci
I plain forgot to run them in the `ci` script.
> Actually run the tests

- package.json
- yarn.lock
Parcel kept adding this to my package.json, so I relent.
> Add TypeScript dep

- ci
- package/src/handler.test.ts
(no need for review) I'm not sure how CI passed on https://buildkite.com/sourcegraph/sourcegraph-basic-code-intel/builds/57#66c614e4-cf59-433e-b704-4993b6114adf because it fails locally for me. Anyway, this fixes it.
> Fix test/CI

- languages.ts
> No need for review because this follows the same approach as filtering definitions for Go.
This helps, but since most Java symbols are already unique, it doesn't improve code intel as much as for Go.
> Filter definitions by imports for Java

- languages.ts
- package.json
- package/src/handler.ts
- yarn.lock
> No need for review, same approach as usual.
> Filter definitions by imports for TypeScript

- languages.ts
> No need for review, since this follows the usual approach.
> Filter definitions by imports for Python

- package/package.json
- package/yarn.lock
> No need for review, I forgot to remove this when I removed definition patterns.
> Rm sprintf js

- languages.ts
> Filter definitions by imports for C++

- languages.ts
> No need for review, straightforward continuation of https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/85
> Improve the C++ definition filter

- package/package.json
- package/src/index.ts
> No need for review, this brings back old code.
> Export activateBasicCodeIntel

- languages.ts
Fixes https://github.com/sourcegraph/sourcegraph/issues/3550
> Recognize Arduino .ino files as C/C++

- template/README.md
Each language extension no longer has its own repository.
> Fix link to repository

- package/package.json
- package/src/handler.test.ts
- package/src/index.ts
- package/yarn.lock
- template/src/extension.ts
- template/tsconfig.json
> Activate LSIF for basic code intel

- package/package.json
Includes https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/145
> 7.0.6 to ignore LSIF errors

- languages.ts
Some organizations use .cxx files as c++ source files.
> Recognize .cxx files as C/C++

- package/package.json
Includes https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/160
> Bump version

- package/package.json
- package/src/handler.test.ts
- package/src/handler.ts
Fixes https://github.com/sourcegraph/sourcegraph/issues/6540
> Fix literal dot in file extension filter

- package/package.json
- package/src/lsif.ts
This handles https://github.com/sourcegraph/sourcegraph/issues/6656.
> Print log message when LSIF data is available

- template/package.json
> LSIF improvements

- languages.ts
Allowed characters (now outdated): https://stackoverflow.com/a/3961674
Arrows: https://stackoverflow.com/questions/21189499/arrow-in-function-name-in-clojure
> Add additional permitted characters to Clojure

- package/package.json
Bump version after UI indicators landed. This seems like a major release!
> Bump version to v9.

- template/package.json
Fixes https://github.com/sourcegraph/sourcegraph/issues/28973
@tjkandala Is this what you had in mind when you said ["Could they check that the current language also matches the extension's language?"](https://github.com/sourcegraph/sourcegraph/pull/29853#issuecomment-1016606604)?
> Fix duplicate find-implementations button

- template/package.json
A follow-up to https://github.com/sourcegraph/code-intel-extensions/pull/821
> Remove icon from the ref panel action button 
