package.json
src/api.ts
src/extension.ts
src/handler.ts
yarn.lock

- Add a panel action "Show/hide fuzzy matches" to references/definitions panel
- Default to using symbols locally
- Add an action to switch between using symbols locally
- Coexist with precise code intelligence better
- Only use old toggle action (that disables all `langserver/*` extensions) on pre-3.0 versions of Sourcegraph
These improvements are intended to make it possible to enable basic code intel for all users on Sourcegraph.com.
fixes https://github.com/sourcegraph/sourcegraph/issues/1175

feat: use new extension APIs for better UX

---

package.json
src/api.ts
src/extension.ts
src/handler.test.ts
src/handler.ts
src/memoizeAsync.ts

**Depends on https://github.com/sourcegraph/sourcegraph/pull/1313.**
If `basicCodeIntel.hover` is enabled in user settings, this extension will provide hovers consisting of:
- the best-guess definition line's code, cleaned up a bit (e.g., removing trailing `:`s)
- the docstring before or after the definition line
It only shows a hover if the definition location can be found using symbols. If no results are found using symbols, it does not fall back to text search for generating hover contents because that is too inaccurate.
The `basicCodeIntel.hover` setting is off by default.

provide hovers + enhance heuristics for definitions

---

src/extension.ts

2.13 did not support getting config synchronously in the activate call, so we need to wrap it in setTimeout. This adds nearly imperceptible lag on newer versions.
fixes https://github.com/sourcegraph/sourcegraph/issues/1993

fix: defer getting config for 2.13 backcompat

---

generator/src/main.ts
languages.ts
package/package.json
package/src/index.ts
template/package.json
template/src/extension.ts

Users are often times confused why imprecise references are shown in the references panel after clicking "Find references". This happens for languages that do not have a language server and for Sourcegraph instances that don't have a language server deployed.
This adds an "Imprecise results" label (technically an action) to the references panel. Here's what it looks like when you haven't set up a language server yet:
When there is no language server for the current language, the second sentence is dropped.
When you have the `{go,typescript,python}.serverUrl` set, the label is not shown.

Add an "Imprecise results" label to references

---

package/package.json
package/src/api.ts

This used to `JSON.stringify` something that contained `sourcegraph`, which must have some circular references. I believe this is causing https://github.com/sourcegraph/sourcegraph-python/issues/7.

Fix JSON.stringify on circular value

---

languages.ts
package/src/handler.test.ts
package/src/handler.ts

I had first introduced [definition patterns](https://sourcegraph.slack.com/archives/CCLF4R6EM/p1549020484180600?thread_ts=1549020484.180600) to:
- Support languages that ctags didn't support (invalidated by https://github.com/sourcegraph/sourcegraph/pull/2139)
- Recognize bindings such as `bar, err := ...` in Go (turns out to be rather confusing because it's [wildly inaccurate](https://github.com/sourcegraph/sourcegraph/issues/2651))
- Cross-repository search was too expensive until I [sped up symbol search](https://github.com/sourcegraph/sourcegraph/pull/2334)
Fixes https://github.com/sourcegraph/sourcegraph/issues/2651

Replace definition patterns with cross-repository symbol search

---

template/package.json

Fixes https://github.com/sourcegraph/sourcegraph/issues/2700

Lowercase "l" in "Programming languages"

---

generator/src/main.ts
template/package.json

See https://sourcegraph.slack.com/archives/C0W2E592M/p1552345895027600?thread_ts=1552342240.006400&cid=C0W2E592M

s/Imprecise results/References: Search mode/

---

package/src/api.ts
package/src/handler.ts

When you set `"codeintel.debug": true`, each line that contains a symbol definition will be highlighted:

Add debug mode

---

package/src/api.ts
package/src/handler.ts

Otherwise this would throw an error on Sourcegraph instances that don't support `fileLocal` (none as of yet, working on a PR for it now).

Only query for fileLocal if codeintel.debug is specified

---

package/src/handler.ts

When `feature.fileLocal` is set, file-local definitions will be filtered out.
File-local definitions are being added in (TODO link).

Filter by fileLocal

---

package/src/handler.ts

The default limit of 30 was too low to show all symbols in mux.go.

Bump debug symbol count

---

package/src/api.ts
package/src/handler.ts

It's difficult to determine whether or not the Sourcegraph instance that basic-code-intel is running on supports the [`fileLocal` GraphQL field](https://github.com/sourcegraph/sourcegraph/pull/2788), so use a setting for now.

Toggle fileLocal based on a setting

---

generator/src/main.ts
languages.ts
template/src/extension.ts
template/src/languages.ts

Previously, the generator would write out a TypeScript file using string interpolation, which only worked for arguments that were `JSON.stringify`able.
Now, the arguments are referred to directly, so callbacks can be added.

Avoid templating TypeScript, enables callbacks

---

languages.ts
package/package.json
package/src/handler.ts
template/package.json
template/yarn.lock

See https://github.com/sourcegraph/sourcegraph/issues/2298

Add support for filtering definitions by import path

---

package/src/handler.ts

(no need for review) Works around https://github.com/universal-ctags/ctags/issues/1844 by considering all enums in Java public. Previously, all enums in Java were private.

Work around Java bug in ctags

---

languages.ts

This matches `require('foo').bar`.

Improve TypeScript import regex

---

package/src/handler.test.ts
package/src/handler.ts
template/yarn.lock

Prior to this change, basic code intel would run 3 separate searches, returning early when one returns any results:
- Current file
- Current repository
- All repositories (unless on Sourcegraph.com)
This prevented basic code intel from showing valid results and letting the user choose (see https://github.com/sourcegraph/sourcegraph/issues/3234)
After this change, basic code intel will run 2 searches (skipping the current file search):
- Current repository
- All repositories (unless on Sourcegraph.com)
One reason why I didn't do this earlier is because j2d was very imprecise. Filtering by imports vastly improves this and tips the scale.
Fixes https://github.com/sourcegraph/sourcegraph/issues/3234 it'll show a choice after this change instead of jumping to the `Main` defined in the same …

Remove same-file search query

---

package/package.json
package/src/handler.ts
package/src/index.ts
template/package.json
template/src/extension.ts

This shows a little smiley face icon in the toolbar for submitting feedback about basic code intel (links to a Google Form):
Global/org/user setting:
```
// Shows the little smiley face icon in the toolbar for submitting feedback about basic code intel.
"basicCodeIntel.showFeedback": true,
```
The plan is to turn this on for the Sourcegraph org (teammates only) to determine in which areas basic code intel could most improve and have the most benefit. 99% of customers in the pipeline use basic code intel, so this aligns our experience with theirs.

Add button to submit feedback

---

package/package.json

The previous release build had a `<reference...` comment at the top of https://unpkg.com/@sourcegraph/basic-code-intel@6.0.16/lib/api.d.ts which caused the sourcegraph-typescript build to fail https://buildkite.com/sourcegraph/sourcegraph-typescript/builds/1621#be145b1a-0e75-49f1-9f69-11c4b5c4be8f/19-89
This was because I had the `sourcegraph` package linked locally.

Bump basic-code-intel 6.0.17

---

codecov.yml
package/src/handler.test.ts
package/src/handler.ts

This adds a setting to disable global symbol search:
```json
"codeIntel.globalSymbolSearch": false
```
Defaults to **`true`** (the current behavior).
The downside is that when this is `false`, cross-repository go-to-definition will stop working.
See https://sourcegraph.slack.com/archives/C08JA8Q1H/p1563496178024000?thread_ts=1563233415.015100&cid=C08JA8Q1H

Add toggle for global symbol search

---

generator/src/main.ts

Because of performance issues, the Python language server has been disabled for months and we do not recommend using it. That makes http://github.com/sourcegraph/sourcegraph-python a no-op wrapper around basic-code-intel, so we might as well generate it from this repo.

Also generate sourcegraph-python

---

package/package.json
package/src/index.ts
package/src/lsif.ts

https://github.com/sourcegraph/sourcegraph-typescript/pull/229 could make use of some more functions from basic-code-intel to avoid needing to unwrap values as much and to avoid submodule imports.
See https://github.com/sourcegraph/sourcegraph-typescript/pull/229#discussion_r312515617

Export more functions from the top level

---

package/src/lsif.ts

This is a quick fix because code intel appears to be broken right now.

Interpret a non-OK response as no LSIF available

---

Procfile
dev

Otherwise I get errors such as: `error An unexpected error occurred: "https://registry.yarnpkg.com/tslib/-/tslib-1.10.0.tgz: ENOENT: no such file or directory, open '/Users/chrismwendt/Library/Caches/Yarn/v4/npm-tslib-1.10.0-c3c19f95973fb0a62973fb09d90d961ee43e5c8a/node_modules/tslib/.yarn-tarball.tgz'".`

Run yarn in series so it's more reliable

---

package/src/api.ts
package/src/handler.ts

The problem here was that basic-code-intel was not decoding the URL fragment (the part after the `#`), which broke code intel on files with special characters.
Fixes https://github.com/sourcegraph/sourcegraph/issues/6042

Decode the fragment

---

package/src/handler.test.ts
package/src/handler.ts

Now that symbol search is indexed, it's no longer a perf concern.
Resolves https://github.com/sourcegraph/sourcegraph/issues/6755
Reverts https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/123

Remove codeIntel.globalSymbolSearch

---

package/package.json
package/src/handler.ts
package/src/lsif.ts
package/src/lsp-conversion.ts
template/src/extension.ts

Implements [RFC 49 REVIEW: Fallback when LSIF data doesn't exist](https://docs.google.com/document/d/1qONlFV3mkNZLfO3KyYlEApez1tLYt3BkOAqJxvUeuRk/edit)
Prior to this change, if there was no LSIF results for a code intel request, no code intel would be presented to the user.
After this change:
- Hovers: if LSIF returns no hover, it'll fall back to basic-code-intel
- Definitions: if LSIF returns no definition, it'll fall back to basic-code-intel
- References: **both** LSIF **and** text search results are shown, LSIF first
Related: [RFC 89 WIP: Precise Code Intel Confidence](https://docs.google.com/document/d/1aVbkz-yIBHNdrubkYq9vUrVa7_yUUVSPMmwvy52hRXc/edit#heading=h.trqab8y0kufp) outlines a plan to make the source of code intel data more transparent to the user so they understand why …

Fall back to fuzzy because LSIF data might be sparse

---

template/src/extension.ts

No need to bump the version because this doesn't affect the API.
Original thread https://sourcegraph.slack.com/archives/CHXHX7XAS/p1576271772003500

Drop fuzzy results from files that have LSIF results

---

package/package.json
package/src/handler.ts
package/src/lsif.ts
package/src/versions.test.ts
package/src/versions.ts
package/yarn.lock
template/src/extension.ts

This is an update to support the GraphQL API for LSIF data (once https://github.com/sourcegraph/sourcegraph/pull/7021 is merged).
The version check might be wonky: not sure a better way than to do it date-based. That will allow a transition period where both APIs are available (for at least one day). The date string there is currently wrong (obviously) and must be updated after the dependent PR is merged.

LSIF GraphQL API

---

package.json

The `github:OWNER/REPO` syntax might be handled specially by some tools, but it's non-standard. It also breaks the `Repository` link on the extension's page at (eg) https://sourcegraph.com/extensions/sourcegraph/go.

Use standard URL in package.json repository object

---

template/package.json

Calling `sub()` on older versions of Sourcegraph throws an error because `commandArguments` are evaluated eagerly (rather than lazily once the command is triggered):

Guard use of sub()

---

template/package.json

This PR changes the action button text to address the [issue with the overflowing text](https://github.com/sourcegraph/sourcegraph/issues/39517).

Add tooltip to the extensions panel search/precise results action button
